### ISSUE TITLE
Problems with -s

### ISSUE THREAD

**Issue by dloscutoff** [mbuettner/retina#32]
Suppose the existence of the following files:

    test.rgx:  .
    test.rpl:  X
    test.ret:  .\nX  (where \n is an actual newline)
    input.txt: Hello!

1. Invoking `Retina test.rgx test.rpl < input.txt` gives `XXXXXX`, as expected.
1. Invoking `Retina -s test.ret < input.txt` gives `Hello!`.
1. Invoking `Retina -s test.ret` and entering `Hello!` on stdin gives `HelloX`.

**Comment by mbuettner** [comment]
Try `cat input.txt | Retina -s test.ret` maybe? It's the only form I've ever tested. What platform are you on?

**Comment by dloscutoff** [comment]
Windows 7; I don't have a `cat` command, but I do have `type`. On further investigation, the above example does work when I use Unix-style newlines in the `.ret` file; but I have a more-complicated program that still fails. I'll try to boil it down to a simpler version.

**Comment by dloscutoff** [comment]
My more-complicated program had a bug--once fixed, it worked as expected. So I guess this boiled down in the end to: make sure when using `-s` that the file has Unix newlines.

**Comment by mbuettner** [comment]
Ah, yes that's right. Retina splits the files on linefeed characters, so
all your patterns try to match an `\r` at the end. Might be worth
documenting
