### ISSUE TITLE
$#+ doesn't work

### ISSUE THREAD

**Issue by randomra** [mbuettner/retina#41]
Special substitutions ``$+`` doesn't work together with the "number of captures" substitution syntax (``$#+``).  ``$#` $#' $#_ $#&`` doesn't work either but those make little sense anyway (i.e. aliases for `0`).

Example code for empty input:
```
^
abcdefghijk
f(g)h
$#+ $#` $#' $#_ $#0 $#1
```

**Comment by mbuettner** [comment]
I've implemented `$#+`. I don't think there's any point in adding the others.
