### ISSUE TITLE
Transliterate mode with remove and subtitution in one phase

### ISSUE THREAD

**Issue by randomra** [mbuettner/retina#48]
This would be doable with a character (e.g. `r`) assigned to removal in the `to` part of the expression. It could expand as any other characters or classes.

E.g. change digits to their modulo 3 value while removing lowercase letters:
``T`dl`0120120120r``

**Comment by mbuettner** [comment]
Interesting idea. I might go with something else like `_` instead of `r`, but I like it.

**Comment by mbuettner** [comment]
Implemented in be7294d.
